Skip the faling tests
This is because of the `python` executable being expected.

```
=================================== FAILURES
===================================
________________ TestEMRutils.test_which_with_existing_command
_________________

self = <tests.unit.customizations.emr.test_emr_utils.TestEMRutils object
at 0x7f2aefd4bb90>

    def test_which_with_existing_command(self):
        pythonPath = which('python') or which('python.exe')
>       assert pythonPath is not None
E       assert None is not None

unit/customizations/emr/test_emr_utils.py:21: AssertionError
_________ TestKinesisRemoveOperations.test_subscribe_to_shard_removed
__________

self =
<tests.functional.kinesis.test_remove_operations.TestKinesisRemoveOperations testMethod=test_subscribe_to_shard_removed>

    def test_subscribe_to_shard_removed(self):
        result = aws('kinesis subscribe-to-shard help')
        error_msg = 'argument operation: Invalid choice, valid choices
are:'
>       self.assertIn(error_msg, result.stderr)
E       AssertionError: 'argument operation: Invalid choice, valid
choices are:' not found in '/bin/sh: line 1: python: command not
found\n'

functional/kinesis/test_remove_operations.py:21: AssertionError
------------------------------ Captured log call
-------------------------------
DEBUG    awscli.tests.integration:testutils.py:626 Running command:
python
/builddir/build/BUILDROOT/awscli-2-2.4.19-2.20221108094828506649.develop.fc37.x86_64/usr/bin/aws kinesis subscribe-to-shard help
DEBUG    awscli.tests.integration:testutils.py:561 rc: 127
DEBUG    awscli.tests.integration:testutils.py:562 stdout:
DEBUG    awscli.tests.integration:testutils.py:563 stderr: /bin/sh: line
1: python: command not found
_______ TestLexV2RuntimeRemoveOperations.test_start_conversation_removed
_______

self =
<tests.functional.lex.test_remove_operations.TestLexV2RuntimeRemoveOperations testMethod=test_start_conversation_removed>

    def test_start_conversation_removed(self):
        result = aws('lexv2-runtime start-conversation help')
        error_msg = 'argument operation: Invalid choice, valid choices
are:'
>       self.assertIn(error_msg, result.stderr)
E       AssertionError: 'argument operation: Invalid choice, valid
choices are:' not found in '/bin/sh: line 1: python: command not
found\n'

functional/lex/test_remove_operations.py:21: AssertionError
------------------------------ Captured log call
-------------------------------
DEBUG    awscli.tests.integration:testutils.py:626 Running command:
python
/builddir/build/BUILDROOT/awscli-2-2.4.19-2.20221108094828506649.develop.fc37.x86_64/usr/bin/aws lexv2-runtime start-conversation help
DEBUG    awscli.tests.integration:testutils.py:561 rc: 127
DEBUG    awscli.tests.integration:testutils.py:562 stdout:
DEBUG    awscli.tests.integration:testutils.py:563 stderr: /bin/sh: line
1: python: command not found
=============================== warnings summary
===============================
../../../../../usr/lib/python3.11/site-packages/botocore/utils.py:15
  /usr/lib/python3.11/site-packages/botocore/utils.py:15:
DeprecationWarning: 'cgi' is deprecated and slated for removal in Python
3.13
    import cgi

unit/test_paramfile.py:95
  /builddir/build/BUILD/awscli-2-2.4.19/tests/unit/test_paramfile.py:95:
DeprecationWarning: invalid escape sequence '\.'
    with self.assertRaisesRegex(ResourceLoadingError, 'foo\.bar\.baz'):

unit/test_paramfile.py:100

/builddir/build/BUILD/awscli-2-2.4.19/tests/unit/test_paramfile.py:100:
DeprecationWarning: invalid escape sequence '\.'
    with self.assertRaisesRegex(ResourceLoadingError, 'foo\.bar\.baz'):

unit/test_utils.py:70
  /builddir/build/BUILD/awscli-2-2.4.19/tests/unit/test_utils.py:70:
DeprecationWarning: invalid escape sequence '\,'
    self.assertEqual(split_on_commas('foo,bar=1\,2\,3,baz'),

unit/customizations/emr/test_add_steps.py:215

/builddir/build/BUILD/awscli-2-2.4.19/tests/unit/customizations/emr/test_add_steps.py:215: DeprecationWarning: invalid escape sequence '\,'
    'Properties=k1=v1\,k2=v2\,k3')

unit/customizations/history/test_db.py:618

/builddir/build/BUILD/awscli-2-2.4.19/tests/unit/customizations/history/test_db.py:618: DeprecationWarning: invalid escape sequence '\e'
    'tuple': ('bar', 'baz', b'\xfe\ed')

functional/cloudformation/test_create_stack.py:44

/builddir/build/BUILD/awscli-2-2.4.19/tests/functional/cloudformation/test_create_stack.py:44: DeprecationWarning: invalid escape sequence '\,'
    cmdline += ' --parameters ParameterKey=foo,ParameterValue=one\,two'

../../../BUILDROOT/awscli-2-2.4.19-2.20221108094828506649.develop.fc37.x86_64/usr/lib/python3.11/site-packages/awscli/testutils.py:916

/builddir/build/BUILDROOT/awscli-2-2.4.19-2.20221108094828506649.develop.fc37.x86_64/usr/lib/python3.11/site-packages/awscli/testutils.py:916: PytestCollectionWarning: cannot collect test class 'TestEventHandler' because it has a __init__ constructor (from: tests/functional/elb/test_register_instances_with_load_balancer.py)
    class TestEventHandler(object):

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
=========================== short test summary info
============================
FAILED
unit/customizations/emr/test_emr_utils.py::TestEMRutils::test_which_with_existing_command
FAILED
functional/kinesis/test_remove_operations.py::TestKinesisRemoveOperations::test_subscribe_to_shard_removed
FAILED
functional/lex/test_remove_operations.py::TestLexV2RuntimeRemoveOperations::test_start_conversation_removed
====== 3 failed, 13696 passed, 5 skipped, 8 warnings in 247.03s
(0:04:07) ======
Running pytest unit/ functional/...
Traceback (most recent call last):
  File "/builddir/build/BUILD/awscli-2-2.4.19/scripts/ci/run-tests",
line 71, in <module>
    run(cmd)
  File "/builddir/build/BUILD/awscli-2-2.4.19/scripts/ci/run-tests",
line 31, in run
    return check_call(command, shell=True, env=env)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/subprocess.py", line 413, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'pytest unit/ functional/'
returned non-zero exit status 1.
error: Bad exit status from /var/tmp/rpm-tmp.4VC7PL (%check)

```

Signed-off-by: Frantisek Lachman <flachman@redhat.com>